### ISSUE TITLE
Disable Park Assistance over CAN ?

### ISSUE THREAD

**Issue by unref-ptr** [projectgus/hyundai-kona-ev-can-logs#1]
Thanks a lot for the work on this repo. Do you think it is possible to disable the Park Distance Control via CAN ? I.e. sending a CAN Msg that disables it, or is this only possible over the switch.

I found this

![stlbe6110l](https://github.com/projectgus/hyundai-kona-ev-can-logs/assets/81707041/4270b243-3a75-4adb-b5c6-7381bf05f8db)

So I am not sure if I can make send something to the BCM ?

**Comment by projectgus** [comment]
Hi @unref-ptr,

Interesting question. I don't know as I haven't looked into the parking sensor system at all, but I expect probably not.

I would guess that most likely whichever module (cluster or BCM) the enable/disable switch is wired to will send the status as a signal in a CAN message that is sent multiple times a second.

If the switch is wired to the BCM (seems likely) then probably the best you could hope for would be to monitor the BCM output (on either CAN or LIN) to tell if the sensors are enabled, and also simulate a button press on the button input pin to switch that setting if needed...

It might be easier to make something to disconnect the buzzer (either permanently or with a switch).

That's all 100% guesses, though. I don't think any of the CAN logs in this repo are doing anything of note with the parking sensors.

**Comment by unref-ptr** [comment]
Thanks for the feedback. I guess I will close this issue for now as I have not had any progress.
